title: Default Page
preset: page
fields:
  text:
    label: Text
    type: layout
    size: large
    layouts:
      - "1/1"
      - "1/2, 1/2"
    fieldsets:
      - code
      - gallery
      - heading
      - list
      - markdown
      - quote
      - text
      - video
      - button

      image:
        extends: blocks/image
        fields:
          round:
            label: Round Image
            type: toggle
