title: Site

tabs:
  content:
    label: Pages
    preset: pages
    unlisted: true
    pages: true
  config:
    label: Global configuration
    fields:
      twitter:
        label: Twitter
        type: text
        width: 1/2
      linkedin:
        label: LinkedIn
        type: text
        width: 1/2
