title: Default Page
tabs:
  content:
    label: Content
    icon: pen
    preset: page
    pages: false
    fields:
      text:
        label: Text
        type: layout
        size: large
        layouts:
          - "1/1"
          - "1/2, 1/2"
          - "1/4, 1/4, 1/4, 1/4"
          - "1/1, 1/4, 1/4, 1/4, 1/4"
        fieldsets:
          - code
          - gallery
          - heading
          - list
          - markdown
          - quote
          - text
          - video
          - externallink

          image:
            extends: blocks/image
            fields:
              round:
                label: Round Image
                type: toggle
  seotab: seo